import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--aw-font-sans" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} 2xl:text-[20px]`}>
      <body className="antialiased text-page bg-light dark:text-slate-300 tracking-tight dark:bg-dark">
        {children}
      </body>
    </html>
  );
}
